/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    posts: Post;
    tags: Tag;
    media: Media;
  };
  globals: {};
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Post {
  postMeta: {
    title: string;
    description: string;
    keywords?: string;
  };
  title: string;
  id: string;
  hero?: string | Media;
  intro?: {
    [k: string]: unknown;
  }[];
  tableofcontents?: {
    title?: string;
    subtitle?: {
      title?: string;
      id?: string;
    }[];
    id?: string;
  }[];
  layout?: (
    | {
        quote?: string;
        author?: string;
        id?: string;
        blockName?: string;
        blockType: 'quote';
      }
    | {
        content?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        type?: 'info' | 'success' | 'warning' | 'danger';
        message?: string;
        id?: string;
        blockName?: string;
        blockType: 'alert';
      }
  )[];
  template?: 'guide' | 'regular';
  status?: 'draft' | 'published';
  publishedDate?: string;
  author?: string | User;
  tags?: string[] | Tag[];
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  alt?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Tag {
  id: string;
  name: string;
  posts?: string[] | Post[];
  updatedAt: string;
  createdAt: string;
}
